{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "**Содержание**<a id='toc0_'></a>    \n",
    "- [Обработка ошибок](#toc1_)    \n",
    "  - [Логические ошибки и исключительные ситуации](#toc1_1_)    \n",
    "  - [Выявление логических ошибок на этапе разработки](#toc1_2_)    \n",
    "  - [Способы сообщения об ошибке](#toc1_3_)    \n",
    "  - [Исключения](#toc1_4_)    \n",
    "  - [Stack unwinding](#toc1_5_)    \n",
    "  - [Почему не стоит бросать встроенные типы?](#toc1_6_)    \n",
    "  - [Стандартные классы исключений](#toc1_7_)    \n",
    "  - [Исключения в стандартной библиотеке](#toc1_8_)    \n",
    "  - [Как обрабатывать ошибки?](#toc1_9_)    \n",
    "  - [Исключения в деструкторах и конструкторах](#toc1_10_)    \n",
    "    - [Исключения в деструкторах](#toc1_10_1_)    \n",
    "    - [Исключения в конструкторе](#toc1_10_2_)    \n",
    "    - [Исключения в списке инициализации](#toc1_10_3_)    \n",
    "- [Спецификация исключений](#toc2_)    \n",
    "  - [Спецификация исключений](#toc2_1_)    \n",
    "  - [Ключевое слово noexcept](#toc2_2_)    \n",
    "  - [noexcept для деструктора](#toc2_3_)    \n",
    "  - [Использование noexcept](#toc2_4_)    \n",
    "  - [Условный noexcept](#toc2_5_)    \n",
    "  - [Зависимость от noexcept](#toc2_6_)    \n",
    "- [Гарантии безопасности исключений](#toc3_)    \n",
    "  - [Гарантии безопасности исключений](#toc3_1_)    \n",
    "  - [Строгая гарантия безопасности исключений](#toc3_2_)    \n",
    "  - [Как добиться строгой гарантии?](#toc3_3_)    \n",
    "  - [Как добиться строгой гарантии: вручную](#toc3_4_)    \n",
    "  - [Как добиться строгой гарантии: RAII](#toc3_5_)    \n",
    "  - [Как добиться строгой гарантии: swap](#toc3_6_)    \n",
    "  - [Проектирование с учётом исключений](#toc3_7_)    \n",
    "  - [Проектирование с учётом исключений (продолжение)](#toc3_8_)    \n",
    "  - [Использование unique_ptr](#toc3_9_)    \n",
    "  - [Заключение](#toc3_10_)    \n",
    "\n",
    "<!-- vscode-jupyter-toc-config\n",
    "\tnumbering=false\n",
    "\tanchor=true\n",
    "\tflat=false\n",
    "\tminLevel=1\n",
    "\tmaxLevel=6\n",
    "\t/vscode-jupyter-toc-config -->\n",
    "<!-- THIS CELL WILL BE REPLACED ON TOC UPDATE. DO NOT WRITE YOUR TEXT IN THIS CELL -->"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# <a id='toc1_'></a>[Обработка ошибок](#toc0_)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## <a id='toc1_1_'></a>[Логические ошибки и исключительные ситуации](#toc0_)\n",
    "\n",
    "**Логические ошибки.**\n",
    "\n",
    "Ошибки в логике работы программы, которые происходят из-за неправильно написанного кода, т.е. это ошибки программиста:\n",
    "\n",
    "- выход за границу массива,\n",
    "- попытка деления на ноль,\n",
    "- обращение по нулевому указателю,\n",
    "- . . .\n",
    "\n",
    "**Исключительные ситуации.**\n",
    "\n",
    "Ситуации, которые требуют особой обработки. Возникновение таких ситуаций — это „нормальное“ поведение программы.\n",
    "\n",
    "- ошибка записи на диск,\n",
    "- недоступность сервера,\n",
    "- неправильный формат файла,\n",
    "- . . ."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## <a id='toc1_2_'></a>[Выявление логических ошибок на этапе разработки](#toc0_)\n",
    "\n",
    "**Оператор** static_assert (`static` == проверки на этапе компиляции)\n",
    "\n",
    "    #include<type_traits>   // is_integral is_signed - на этапе компиляции\n",
    "\n",
    "    // #defunt NDEBUG          // все ассерты рантайма превращаются в nop\n",
    "    #include <cassert>      // assert (макрос) - не этапе выполнения\n",
    "    \n",
    "    template<class T>\n",
    "    void countdown(T start) {\n",
    "        static_assert(std::is_integral<T>::value && std::is_signed<T>::value,\n",
    "                      \"Requires signed integral type\");\n",
    "        \n",
    "        assert(start >=0);\n",
    "\n",
    "        while (start >= 0) {\n",
    "            std::cout << start-- << std::endl;\n",
    "        }\n",
    "    }\n",
    "\n",
    "макрос `assert`\n",
    "\n",
    "    #ifdef NDEBUG\n",
    "    #  define assert(condition) ((void)0)\n",
    "    #else\n",
    "    #  define assert(condition) /*implementation defined*/\n",
    "    #endif\n",
    "\n",
    "Если очень хочется сообщение об ошибке, то можно добавить строку к условию.\n",
    "    \n",
    "    assert(x > 0 && \"Message\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "**Тест**\n",
    "\n",
    "Выберите типы с которым следующий static_assert не вызовет ошибку компиляции.\n",
    "\n",
    "    static_assert( std::is_arithmetic<T>::value || \n",
    "                (std::is_pointer<T>::value && \n",
    "                    std::is_class<typename std::remove_pointer<T>::type>::value), \n",
    "            \"T can not be used here\" );\n",
    "\n",
    "- T должен быть или числовым (int/float) или указателем на класс\n",
    "\n",
    "\n",
    "**да** int / std::string *\n",
    "\n",
    "**нет** int * / std::vector<int> / std::vector<int*> / std::string\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## <a id='toc1_3_'></a>[Способы сообщения об ошибке](#toc0_)\n",
    "\n",
    "Пусть есть функция:\n",
    "\n",
    "    size_t write(string file, string data);\n",
    "\n",
    "Сообщить об ошибке можно так:\n",
    "\n",
    "**Возврат статуса операции** - была ли ошибка (перепеписать функцию или обернуть):\n",
    "    \n",
    "    bool write(string file, string data, size_t & bytes);\n",
    "\n",
    "**Возврат кода ошибки** - аналогично + заводятся константы/перечисление кодов ошибок:\n",
    "\n",
    "    int const OK = 0, IO_WRITE_FAIL = 1, IO_OPEN_FAIL = 2;\n",
    "    int write(string file, string data, size_t & bytes);\n",
    "\n",
    "\n",
    "**Глобальная переменная** для кода ошибки - сигнатуру функции менять не потребуется, но функцию менять все равно придется (так делается в С-style) - проверяем глобальную переменную, в которую должна писать `write`:\n",
    "\n",
    "    size_t write(string file, string data);\n",
    "\n",
    "    size_t bytes = write(f, data);\n",
    "    if (errno) {\n",
    "        cerr << strerror(errno);\n",
    "        errno = 0;\n",
    "    }\n",
    "\n",
    "*) глобальная переменная - это хуже изменения сигнатуры, т.к. код становится немасштабируемым, его нельзя будет использовать в многопоточных делах. \n",
    "\n",
    "**Исключения** - не имеют перечисленных выше сложностей\n",
    "\n",
    "Замечания:\n",
    "\n",
    "В защиту `errno` можно отметить, что это не просто глобальная переменная. Часто это макрос, реализующий вызов соответствующей функции, которая реализует доступ к переменной, локальной в смысле потока. Т.е. errno является потокобезопасной, по крайней мере, в POSIX-системах errno своя для каждого потока.\n",
    "\n",
    "В случае классов есть ещё комбинированный вариант - возврат `bool`, а код ошибки класс выдаст по запросу отдельным методом, если он вообще требуется. Такого подхода придерживаются многие C++ библиотеки, самый очевидный пример - Qt, которая ничуть не страдает из-за отсутствия исключений.\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## <a id='toc1_4_'></a>[Исключения](#toc0_)\n",
    "\n",
    "Исключение - это объект с информацией об ошибке\n",
    "\n",
    "    size_t write(string file, string data) {\n",
    "        if (!open(file)) throw FileOpenError(file);\n",
    "        //...\n",
    "    }\n",
    "\n",
    "    double safediv(int x, int y) {\n",
    "        if (y == 0) throw MathError(\"Division by zero\");\n",
    "        return double(x) / y;\n",
    "    }\n",
    "\n",
    "    void write_x_div_y(string file, int x, int y) {\n",
    "        try {\n",
    "            write(file, to_string(safediv(x, y)));\n",
    "        } catch (MathError & s) {\n",
    "            // обработка ошибки в safediv\n",
    "        } catch (FileError & e) {\n",
    "            // обработка ошибки в write\n",
    "        } catch (...) {\n",
    "            // все остальные ошибки (доступа к объекту исключения тут не будет, только факт исключения)\n",
    "        }\n",
    "    }\n",
    "\n",
    "*) `FileOpenError` потомок `FileError` и исключения могут обрабатываться по ссылке на базовый класс"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## <a id='toc1_5_'></a>[Stack unwinding](#toc0_)\n",
    "\n",
    "*) рекомендуют переводить как \"сворачивание стека\", т.к. распространенные варианты \"раскрутка стека\"/\"разворачивание стека\" и т. п. соответствуют неправильной метафоре — на самом деле стек именно \"сворачивается\", т. е. уменьшается, а не \"раскручивается\", т. е. увеличивается.\n",
    "\n",
    "При возникновении исключения объекты на стеке уничтожаются в естественном (обратном) порядке.\n",
    "\n",
    "    void foo() {\n",
    "        D d;\n",
    "        E e(d);\n",
    "        if (!e) \n",
    "            throw F(); // объект F() копируется в спец.буфер для хранения исключений *\n",
    "        G g(e);\n",
    "    }\n",
    "\n",
    "    void bar() {\n",
    "        A a;\n",
    "        try {\n",
    "            B b;\n",
    "            foo();\n",
    "            C c;\n",
    "        } catch (F & f) {\n",
    "            // обработка и пересылка\n",
    "            throw f; // тонкость\n",
    "        }\n",
    "    }\n",
    "\n",
    "*) стандарт не определяет как должен быть устроен буфер исключений, зависит от компиляторв\n",
    "\n",
    "Если брошено исключени в `foo()` локальные переменные удаляются в обр.порядке (Stack unwinding - разворачивание стека):\n",
    "- удаляется `E e(d)` в `foo`\n",
    "- удаляется `D d` в `foo`\n",
    "- выход из `foo();` в `bar`\n",
    "- удаляется `B b` в `bar`\n",
    "- дошли до `try` - конец разворачивания стека, `A a` в `bar` останется на стеке\n",
    "\n",
    "В это случае `C c` и `bar` и `D d` в `foo` не будут созданы.\n",
    "\n",
    "Тонкость. Вместо\n",
    "\n",
    "    throw f;\n",
    "\n",
    "можно (в большинстве случаев лучше) писать просто\n",
    "\n",
    "    throw;\n",
    "\n",
    "тогда будет переслан тот же самый объект класса `F`. Если в блоке catch мы ловим exception f базового класса, то при использовании `throw f` мы делаем копию уже от базового класса и выше по иерархии мы теряем информацию о том исключении, которое было брошено изначально. Так что если нам не нужно бросить новое исключение, а эскалировать текущее, использовать лучше только `throw` без параметров."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## <a id='toc1_6_'></a>[Почему не стоит бросать встроенные типы?](#toc0_)\n",
    "\n",
    "Так делать можно, но не нужно:\n",
    "\n",
    "    int foo() {\n",
    "        if (...) throw -1;\n",
    "        if (...) throw 3.1415;\n",
    "    }\n",
    "\n",
    "    void bar(int a) {\n",
    "        if (a == 0) throw string(\"Not my fault!\");\n",
    "    }\n",
    "\n",
    "Потому что придется ловить именно конкретно этот тип, причем информации об исключении будет крайне мало:\n",
    "\n",
    "    int main () {\n",
    "        try { bar(foo());\n",
    "        } catch (string & s) {\n",
    "            // только текст\n",
    "        } catch (int a) {\n",
    "            // мало информации\n",
    "        } catch (double d) {\n",
    "            // мало информации\n",
    "        } catch (...) {\n",
    "            // нет информации\n",
    "        }\n",
    "    }\n",
    "\n",
    "**Q**. Как происходит сопоставление типа бросаемого объекта и типа в catch в райнтейме, когда типов уже нет как таковых (кроме классов с вирт.методами)? \n",
    "\n",
    "**А**. Зависит от компилятора. В gcc, например, вместе с объектом исключения передаётся и type_info, по которому сопоставляется catch."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## <a id='toc1_7_'></a>[Стандартные классы исключений](#toc0_)\n",
    "\n",
    "Базовый класс для всех исключений (в `<exception>`):\n",
    "\n",
    "    struct exception {\n",
    "        virtual ~exception();\n",
    "        virtual const char* what() const;       // текстовое представление ошибки\n",
    "    };\n",
    "\n",
    "Стандартные классы ошибок (в `<stdexcept>`):\n",
    "\n",
    "- logic_error: \n",
    "    - производные domain_error, invalid_argument, length_error, out_of_range\n",
    "- runtime_error: \n",
    "    - производные range_error, overflow_error, underflow_error\n",
    "\n",
    "Например, чтобы отловить все исключения, унаследованные от `exception`\n",
    "\n",
    "    int main() {\n",
    "        try { ... }\n",
    "        catch (std::exception const& e) {\n",
    "            std::cerr << e.what() << ’\\n’;\n",
    "        }\n",
    "    }\n",
    "\n",
    "*) `catch(...)` по сути нужен только если мы не хотим падения программы с unhandled exception, когда стек вызовов уже развернут до main, а подходящего обработчика так и не нашлось"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## <a id='toc1_8_'></a>[Исключения в стандартной библиотеке](#toc0_)\n",
    "\n",
    "Метод `at` контейнеров array, vector, deque, basic_string,\n",
    "bitset, map, unordered_map бросает `out_of_range`.\n",
    "\n",
    "Оператор `new T` бросает `bad_alloc`.\n",
    "\n",
    "Оператор `new (std::nothrow) T` в возвращает `0`.\n",
    "\n",
    "Оператор `typeid` от разыменованного нулевого указателя бросает `bad_typeid`.\n",
    "\n",
    "Потоки ввода-вывода по умолчанию **не бросают** никаких исключений, только вручную.\n",
    "\n",
    "    std::ifstream file;\n",
    "\n",
    "    // в объект потока маски исключений добавляются так\n",
    "    file.exceptions( std::ifstream::failbit | std::ifstream::badbit ); // Logical error on i/o | Read/writing error on i/o \n",
    "\n",
    "    try {\n",
    "        file.open (\"test.txt\");\n",
    "        cout << file.get() << endl;\n",
    "        file.close();\n",
    "    }\n",
    "    \n",
    "    // тип исключения в потоках определяется так\n",
    "    catch (std::ifstream::failure const& e) {\n",
    "        cerr << e.what() << endl;\n",
    "    }\n",
    "\n",
    "*) У класса ios_base, и как следствие, у всех порождённых от него классов для работы с потоками ввода/вывода, есть четыре флага состояния: goodbit, badbit, eofbit, failbit. Метод exceptions(iostate mask) устанавливает битовую маску, для которой поток будет кидать исключения, если любой из указанных битов состояния был установлен вследствие ошибки. В данном примере исключение будет кидаться, если badbit или failbit установились в состояние true."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## <a id='toc1_9_'></a>[Как обрабатывать ошибки?](#toc0_)\n",
    "\n",
    "Есть несколько „правил хорошего тона“.\n",
    "\n",
    "- Разделяйте „ошибки программиста“ и „исключительные ситуации“.\n",
    "- Используйте assert и static_assert для выявления ошибок на этапе разработки.\n",
    "- В пределах одной логической части кода обрабатывайте ошибки централизованно и однообразно.\n",
    "- Обрабатывайте ошибки там, где их можно обработать.\n",
    "- Если в данном месте ошибку не обработать, то пересылайте её выше при помощи исключения.\n",
    "    - пересылать просто `throw`, чтобы не было копирования и не терялась информация об исходном классе исключения, если оно принималось по ссылке на базовый класс\n",
    "- Бросайте только стандартные классы исключений или производные от них.\n",
    "- Бросайте исключения по значению, а отлавливайте по ссылке \n",
    "    - не будет копирования, при котром тоже м.б. исключение\n",
    "- Отлавливайте все исключения в точке входа.\n",
    "    - это последний шанс поймать исключение, которое ранее нигде не поймалось\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "**Задача**\n",
    "\n",
    "В стандартной библиотеке есть семейство функций to_string для преобразования чисел в строки. Однако обратное преобразование не такое удобное — для каждого числового типа есть своя функция (например, strtoi для int).\n",
    "В данном задании вам предлагается написать шаблонную функцию from_string, которая умеет преобразовывать строку в разные типы. Для реализации from_string предлагается воспользоваться классом std::istringstream, который представляет собой поток ввода из строки, т.е. для преобразования строки в тип T предлагается прочитать значение типа T из потока при помощи оператора >>. В случае неудачного преобразования функция должна бросать исключение bad_from_string, класс которого вам нужно реализовать самостоятельно.\n",
    "\n",
    "Указания\n",
    "\n",
    "- Для того, чтобы учитывать пробельные символы, используйте std::noskipws (например, если строка с числом начинается с пробела или заканчивается пробелом, то это должно быть ошибкой).\n",
    "- При переопределении метода what класса std::exception после сигнатуры метода нужно указывать ключевое слово noexcept (про него будет рассказано позже).\n",
    "- Помните, что считывание std::string из потока означает считывание одного слова (т.е. без пробельных символов), а считывание char — одного символа.\n",
    "- Флаг eof() у потоков устанавливается только, если не удалось прочитать символ: если при чтении из потока с 5-ю символами прочли 5 символов, но при этом 6-ой (отсутствующий) символ прочесть не пытались, то eof() будет выдавать false.\n",
    "- Если Вы определили исключение с ключевым словом class, но не забудьте, что нужно унаследоваться от std::exception с ключевым словом public.\n",
    "- Не забудьте определить конструктор bad_from_string от char const * или от std::string.\n",
    "\n",
    "    #include <string>\n",
    "    #include <sstream>      // istringstream\n",
    "    #include <exception>\n",
    "    \n",
    "    // описание класса исключения bad_from_string\n",
    "    class bad_from_string : public std::exception\n",
    "    {\n",
    "        const std::string info;\n",
    "    public:\n",
    "        bad_from_string(const std::string e =\"from_string exception\") : info(e){}\n",
    "        const char* what() noexcept // noexcept обязательно\n",
    "        {\n",
    "            return info.c_str();\n",
    "        }\n",
    "    };\n",
    "\n",
    "    // функция from_string\n",
    "    template<class Type>\n",
    "    Type from_string(std::string const& s)\n",
    "    {\n",
    "        std::istringstream stream(s);\n",
    "\n",
    "        Type res;\n",
    "        \n",
    "        // std::noskipws не пропускать ' ': строка c пробелами - это ошибка\n",
    "        stream >> std::noskipws >> res;\n",
    "        std::string msg = \"error converting to \";\n",
    "\n",
    "        if (stream.fail()) \n",
    "            throw bad_from_string(msg + typeid(Type).name());\n",
    "        stream.get(); \n",
    "\n",
    "        if(stream.good()) // все ОК, а должен быть EOF!\n",
    "            throw bad_from_string(msg + typeid(Type).name() + \": string has ws chars\");\n",
    "\n",
    "        return res;\n",
    "    }\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## <a id='toc1_10_'></a>[Исключения в деструкторах и конструкторах](#toc0_)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### <a id='toc1_10_1_'></a>[Исключения в деструкторах](#toc0_)\n",
    "\n",
    "Исключения могут использовать в деструкторах и конструкторах как и везде, но!\n",
    "\n",
    "**Исключения не должны покидать деструкторы.** (это ответственность разработчика)\n",
    "\n",
    "Двойное исключение:\n",
    "\n",
    "    void foo() {\n",
    "        try {\n",
    "            Bad b; // исключение в деструкторе\n",
    "            bar(); // исключение\n",
    "        } catch (std::exception & e) {\n",
    "            // ...\n",
    "        }\n",
    "    }\n",
    "\n",
    "- Пусть `Bad b` имеет деструктор, который может бросать исключения. Тогда срабатывание исключения в `bar()` вызывает сворачивание стека и срабатывание деструктора `b`, т.е. во время возникновения одного исключения может возникнуть еще одно (если в деструкторе тоже сработает исключение). С++ предполагает, что одновременно может возникать только 1 исключение, поэтому в таком случае программа гарантированно завершится по сис.вызову `terminate` (без вариантов)\n",
    "\n",
    "Неопределённое поведение:\n",
    "\n",
    "    void bar() {\n",
    "        Bad * bad = new Bad[100];\n",
    "        // ислючение в деструкторе №20\n",
    "        delete [] bad;\n",
    "    }\n",
    "\n",
    "- пусть есть массив объектов в деструкторе элементов которого может бросаться исключение. Если при удалении такого массива в некотором элементе сработает исключение, то удаление массива остановится, исключение будет распространяться по стеку (может где-то и отловится), но суть в том, что массив останется висеть в памяти и не освободит ее, и в нем будут как разрушенные элементы, так и не разрушенные\n",
    "\n",
    "**Тест**\n",
    "\n",
    "Какие из этих конструкций можно указывать в деструкторе, не оборачивая их в try-catch блок.\n",
    "\n",
    "    // 1 исключение нужно перехватить\n",
    "    throw std::runtime_error(\"Some message\");\n",
    "\n",
    "    // 2 может закончиться память std::bad_alloc\n",
    "    int * data = new int[size];\n",
    "\n",
    "    // 3 ОК, std::bad_alloc невозможен\n",
    "    int * data = new (std::nothrow) int[size];\n",
    "\n",
    "    // 4 ОК, предполагается что деструктор корректный \n",
    "    delete [] data;\n",
    "\n",
    "    // 5 s копируется, а вдруг не хватит памяти? std::bad_alloc, а вдруг используется ленивое копирование и самой строки уже нет \n",
    "    // data_ - это поле класса типа std::vector<string>\n",
    "    for (auto s : data_) { len += s.size(); }\n",
    "\n",
    "    // 6 ОК\n",
    "    // data_ - это поле класса типа std::vector<string>\n",
    "    size_t len = 0;\n",
    "    for (auto & s : data_) { len += s.size(); }\n",
    "\n",
    "**3, 4, 6 можно не оборачивать**"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### <a id='toc1_10_2_'></a>[Исключения в конструкторе](#toc0_)\n",
    "\n",
    "В отличие от деструктора покидание исключением конструктора это НОРМА, и даже желательно.\n",
    "\n",
    "Исключения — это единственный способ прервать конструирование объекта и сообщить об ошибке. Можно было бы прервать создание ретурном, но как тогда понять, что это ошибочный объект, он все равно создастся.\n",
    "\n",
    "    struct Database {\n",
    "        explicit Database(string const& uri) {\n",
    "            if (!connect(uri))\n",
    "                throw ConnectionError(uri);\n",
    "        }\n",
    "        ~Database() { disconnect(); }\n",
    "        // ...\n",
    "    };\n",
    "\n",
    "Предположим БД создается в куче, даже в этом случае сворачивание стека будет корректно отработано уничтожение объекта, это так задумано. Деструктор вызываться не будет (он нужен только для корректно созданных объектов по смыслу)\n",
    "\n",
    "    int main() {\n",
    "        try {\n",
    "            Database * db = new Database(\"db.local\");\n",
    "            db->dump(\"db-local-dump.sql\");\n",
    "            delete db;\n",
    "        } catch (std::exception const& e) {\n",
    "            std::cerr << e.what() << ’\\n’;\n",
    "        }\n",
    "    }\n",
    "\n",
    "Замечание:\n",
    "\n",
    "- а если память в куче выделяется в конструкторе и потом бросается исключение? \n",
    "    - тогда память утечет, никто же не знает заранее как устроен код конструктора\n",
    "    - если надо бросать такие исключения, то можно там же в конструкторе их и ловить и обрабатывать (catch-rethrow идиома), но это уже экзотика и применительно к конструкторам не совсем то как он по идее должен использоваться\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### <a id='toc1_10_3_'></a>[Исключения в списке инициализации](#toc0_)\n",
    "\n",
    "**Поля класса создаются перед входом в тело конструктора**. Даже если весь код конструктора завернуть в трайкеч исключения при создании объектов списка инициализации не поймаются. \n",
    "\n",
    "Для этого сделали специальный синтаксис трайкеча: `try` перед списком инициализации и `catch` после определения конструктора\n",
    "\n",
    "Позволяет отловить исключения при создании полей класса.\n",
    "\n",
    "    struct System\n",
    "    {\n",
    "        System(string const& uri, string const& data)\n",
    "        try : db_(uri), dh_(data)\n",
    "        {\n",
    "            // тело конструктора\n",
    "        }\n",
    "        catch (std::exception & e) {\n",
    "            log(\"System constructor: \", e);\n",
    "            throw; // пробрасываем наверх\n",
    "        }\n",
    "    \n",
    "        Database db_;\n",
    "        DataHolder dh_;\n",
    "    };\n",
    "\n",
    "*) если не пробросить исключение из такой конструкции, компилятор сделает это сам, ибо объект то в итоге не создался, полюбому исклоючение надо где-то обрабатывать"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "**Тест**\n",
    "\n",
    "Давайте изучим следующий код (предполагается, что конструкторы классов A и B не бросают исключения, если не указано обратное):\n",
    "\n",
    "    extern bool X;\n",
    "    extern bool Y;\n",
    "\n",
    "    struct A\n",
    "    {\n",
    "        A() { ... }\n",
    "\n",
    "        ~A() \n",
    "        {\n",
    "            try \n",
    "            {\n",
    "                bar();\n",
    "            } \n",
    "            catch (std::exception const & e) \n",
    "            {\n",
    "                log(\"~A()\", e.what());\n",
    "            }\n",
    "        }\n",
    "        B b;\n",
    "    };\n",
    "\n",
    "    void foo() \n",
    "    {\n",
    "        A a;\n",
    "        if (X)\n",
    "            throw std::runtime_error(\"Some message\");\n",
    "    }\n",
    "\n",
    "    void bar() \n",
    "    {\n",
    "        if (Y)\n",
    "            throw std::logic_error(\"Some message\");\n",
    "    }\n",
    "\n",
    "Если при вызове foo() X = false, то и никакое исключение не покинет функцию foo().\n",
    "\n",
    "Если при вызове foo() X = true, то функцию foo() покинет только исключение std::runtime_error.\n",
    "\n",
    "Никакие двойные исключения тут невозможны"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "**Тест**\n",
    "\n",
    "Давайте изучим следующий код:\n",
    "\n",
    "    #include <stdexcept>\n",
    "\n",
    "    extern bool X;\n",
    "\n",
    "    struct MyError : std::runtime_error\n",
    "    {\n",
    "        MyError(char const* s) \n",
    "            : std::runtime_error(s)\n",
    "        {\n",
    "            if (X)\n",
    "                throw std::logic_error(\"Logic error\");\n",
    "        }\n",
    "    };\n",
    "\n",
    "    void foo()\n",
    "    {\n",
    "        throw MyError(\"My error\");\n",
    "    }\n",
    "Если Х, то MyError создан не будет, и бросать нечего\n",
    "\n",
    "**ДА**\n",
    "- Если при вызове foo() X = true, то за пределы функции foo будет выброшено исключение std::logic_error.\n",
    "- Если при вызове foo() X = false, то за пределы функции foo будет выброшено исключение MyError.\n",
    "- Если при вызове foo() X = true, то будет вызван деструктор std::runtime_error.\n",
    "\n",
    "**НЕТ**\n",
    "- Если при вызове foo() X = true, то произойдёт аварийное завершение программы.\n",
    "- Если при вызове foo() X = true, то за пределы функции foo будет выброшено исключение MyError.\n",
    "- Если при вызове foo() X = true, то будет вызван деструктор MyError."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# <a id='toc2_'></a>[Спецификация исключений](#toc0_)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## <a id='toc2_1_'></a>[Спецификация исключений](#toc0_)\n",
    "\n",
    "Устаревшая возможность C++, позволяющая указать список исключений, которые могут быть выброшены из функции. Но в отличие от Java С++ не делает проверки времени компиляции на то, что функции бросают именно эти исключения. Вместо этого делается проверка времени выполнения\n",
    "\n",
    "    void foo() throw(std::logic_error) {\n",
    "        if (...) throw std::logic_error();\n",
    "        if (...) throw std::runtime_error();\n",
    "    }\n",
    "\n",
    "В примере выше, если сработает второй if с непредусмотренным исключением, то программа аварийно завершится. Делается это следущим образом, при компиляции код заменяется на примерно такой:\n",
    "\n",
    "    void foo() {\n",
    "        try {\n",
    "            if (...) throw std::logic_error();\n",
    "            if (...) throw std::runtime_error();\n",
    "        } catch (std::logic_error & e) {\n",
    "            throw e;\n",
    "        } catch (...) {\n",
    "            terminate();\n",
    "        }\n",
    "    }\n",
    "\n",
    "Если сработал второй if, то вызывается terminate()\n",
    "\n",
    "**Короче, не очень удобный механизм, единственное актуальное применение, это указывать пустой список с расчетом на то, что функция не должна бросать исключения, а если бросила, то это аварийное завершение.**\n",
    "\n",
    "    void foo() throw() {...};\n",
    "\n",
    "- т.е. гарантируется остановка именно в той функции, которая нарушила промис о том, что не должна кидать исключения"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## <a id='toc2_2_'></a>[Ключевое слово noexcept](#toc0_)\n",
    "\n",
    "Вместо этого в С++11 появилось новое ключевое слово `noexept`\n",
    "\n",
    "Используется в двух значениях/контекстах:\n",
    "- Спецификатор функции, которая не бросает исключение.\n",
    "- Оператор, проверяющий во время компиляции, что выражение специфицированно как небросающее исключение.\n",
    "\n",
    "Если функцию со спецификацией `noexcept` покинет исключение, то стек **не обязательно** будет свёрнут, перед тем как программа завершится. В отличие от аналогичной ситуации с `throw()`.\n",
    "\n",
    "- Использование спецификации `noexcept` позволяет компилятору лучше оптимизировать код, т.к. не нужно заботиться о сворачивании стека.\n",
    "- Если исключение попытается покинуть `noexcept` метод, то вызывается `std::terminate`\n",
    "\n",
    "*) noexcept не проверяет функцию на наличие явных операторов throw, но компилятор может давать предупреждения "
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "**Тест**\n",
    "\n",
    "Какие методы класса String нужно (можно) специфицировать как noexcept?\n",
    "\n",
    "    Default constructor: 1\n",
    "    Copy constructor:    0\n",
    "    Move constructor:    1\n",
    "    op =:                0\n",
    "    Move op =:           1\n",
    "    size():              1\n",
    "    clear():             1\n",
    "    delete:              1\n",
    "\n",
    "В общем, там, где память может выделятся - нет, возвращается - да, можно noexcept\n",
    "- можно реализовать конструктор по-умолчанию без выделения памяти, а лишь просто проинициализировать данные объекта, т.е. таким образом не будет исключений в таком конструкторе"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## <a id='toc2_3_'></a>[noexcept для деструктора](#toc0_)\n",
    "\n",
    "Отдельно стоит упомянуть, что компилятор может (с C++11 обязан) неявно специфицировать noexcept для деструктора, если вы не сделали это самостоятельно.\n",
    "\n",
    "Например, при выполнении следующего кода программа завершится аварийно после вызова std::terminate, т.к. компилятор неявно специфицирует деструктор  класса A как noexcept.\n",
    "\n",
    "    struct A\n",
    "    {\n",
    "        ~A() { throw std::logic_error(\"Exception is leaving destructor\"); }\n",
    "    };\n",
    "\n",
    "\n",
    "    int main()\n",
    "    {\n",
    "        try\n",
    "        {\n",
    "            A a;\n",
    "        }\n",
    "        catch (std::exception const& e)\n",
    "        {\n",
    "            std::cout << e.what() << std::endl;\n",
    "        }\n",
    "\n",
    "        return 0;    \n",
    "    }"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## <a id='toc2_4_'></a>[Использование noexcept](#toc0_)\n",
    "\n",
    "Пусть есть две функции, одна `noexcept`\n",
    "\n",
    "    void no_throw() noexcept;\n",
    "    void may_throw();\n",
    "\n",
    "Или если структура состоит только из типов, у которых конструкторы `noexcept`, то ее конструктор будет тоже `noexcept`\n",
    "\n",
    "    // копирующий конструктор noexcept\n",
    "    struct NoThrow { int m[100] = {}; };\n",
    "\n",
    "А тут без `noexcept`, точнее `noexcept(false)`\n",
    "\n",
    "    // копирующий конструктор noexcept(false)\n",
    "    struct MayThrow { std::vector<int> v; };\n",
    "\n",
    "Тогда информацию о спецификации noexcept этих типов и выражений от них можно проверять на этапе компиляции\n",
    "\n",
    "    MayThrow mt;\n",
    "    NoThrow nt;\n",
    "    \n",
    "    bool a = noexcept(may_throw()); // false\n",
    "    bool b = noexcept(no_throw()); // true\n",
    "    \n",
    "    bool c = noexcept(MayThrow(mt)); // false\n",
    "    bool d = noexcept(NoThrow(nt)); // true"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## <a id='toc2_5_'></a>[Условный noexcept](#toc0_)\n",
    "\n",
    "В спецификации noexcept можно использовать условные выражения времени компиляции. Функция объявляется компилятором noexcept только если выражение true, иначе объявляется noexcept(false)\n",
    "\n",
    "Например, фунция поэлементного свопа 2 массивов будет компилироваться как `noexcept` если операция свопа их первых элементов `noexcept(true)`:\n",
    "\n",
    "    template <class T, size_t N>\n",
    "    void swap(T (&a)[N], T (&b)[N]) // *\n",
    "                noexcept(noexcept(swap(*a, *b)));\n",
    "\n",
    "*) значение в swap передаются явно по ссылке, хотя массивы и так по умолчанию передаются по ссылке. Они неявно будут преобразованы в указатели. Это видимо сделано так для того, чтобы в функцию можно было передать только реальный массив причем размера N, а не просто приведенный к типу указатель...\n",
    "\n",
    "\n",
    "Или, функция свопа для аналога `std::pair` будет компилироваться как `noexcept` если операция свопа их первых элементов и вторых элементов будет `noexcept(true)`\n",
    "\n",
    "    template <class T1, class T2>\n",
    "    struct pair {\n",
    "        void swap(pair & p)\n",
    "            noexcept(noexcept(swap(first, p.first)) &&\n",
    "                     noexcept(swap(second, p.second)))\n",
    "        {\n",
    "            swap(first, p.first);\n",
    "            swap(second, p.second);\n",
    "        }\n",
    "        \n",
    "        T1 first;\n",
    "        T2 second;\n",
    "    };\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "**Задача**\n",
    "\n",
    "Выше мы воспользовались тем, что функция swap имеет аргументы нужных нам типов. В тех случаях, когда аргументов нужного типа у функции нет, можно использовать std::declval<T>(), который позволяет \"определить\" значение типа T в различных контекстах, в т.ч. в noexcept.\n",
    "\n",
    "Специфицируйте noexcept для шаблонной функции do_math, если известно, что в её реализации значения типа T копируются,  присваиваются и складываются при помощи оператора +.\n",
    "\n",
    "Для простоты будем считать, что перемещающих методов у типа T нет.\n",
    "\n",
    "Пример:\n",
    "\n",
    "    bool b1 = noexcept(do_math<int>()); // true\n",
    "\n",
    "    bool b2 = noexcept(do_math<std::string>()); // false\n",
    "\n",
    "Hint: в данном задании вполне можно обойтись std::declval<T>(), но при желании можно так же заглянуть в библиотеку поддержки типов и найти там подходящую проверку.\n",
    "\n",
    "    #include <utility> // std::declval\n",
    "\n",
    "    // внутри do_math объекты типа T\n",
    "    // - копируются\n",
    "    // - присваиваются\n",
    "    // - складываются оператором +\n",
    "    template<class T>\n",
    "    void do_math() \n",
    "        noexcept(noexcept(std::declval<T>() + std::declval<T>()) \n",
    "                 && std::is_nothrow_copy_constructible<T>::value\n",
    "                 && std::is_nothrow_assignable<T&, T>::value)\n",
    "    {}"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "**Задача**\n",
    "\n",
    "Решите предыдущую задачу в предположении, что у класса T могут быть перемещающие методы.\n",
    "\n",
    "    #include <utility> // std::declval\n",
    "\n",
    "    // внутри do_math объекты типа T\n",
    "    // - копируются\n",
    "    // - присваиваются\n",
    "    // - перемещаются\n",
    "    // - складываются оператором +\n",
    "    template<class T>\n",
    "    void do_math() \n",
    "        noexcept(noexcept(std::declval<T>() + std::declval<T>()) \n",
    "                && std::is_nothrow_copy_constructible<T>::value\n",
    "                && std::is_nothrow_assignable<T&, T>::value\n",
    "                && std::is_nothrow_move_assignable<T&>::value\n",
    "                && std::is_nothrow_move_constructible<T>::value)\n",
    "    {}\n",
    "\n",
    "*) `...assignable` проверялки должны принимать по ссылке аргумент которому присваивается, чтобы не раскрывалось при разборе в, например, для интов `1 = 1`, т.е. должно быть lvalue"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## <a id='toc2_6_'></a>[Зависимость от noexcept](#toc0_)\n",
    "\n",
    "Проверка `noexcept` используется в стандартной библиотеке для обеспечения **строгой гарантии безопасности исключений** с помощью `std::move_if_noexcept` (например, в `vector::push_back` новый объект создается перемещаютщим конструктором, если он noexcept, иначе - копирующим конструктором, что дольше).\n",
    "\n",
    "    struct Bad {\n",
    "        Bad() {}\n",
    "        Bad(Bad&&); // может бросить\n",
    "        Bad(const Bad&); // не важно\n",
    "    };\n",
    "\n",
    "    struct Good {\n",
    "        Good() {}\n",
    "        Good(Good&&) noexcept; // не бросает\n",
    "        Good(const Good&) ; // не важно\n",
    "    };\n",
    "\n",
    "    Good g1;\n",
    "    Bad  b1;\n",
    "\n",
    "    Good g2 = std::move_if_noexcept(g1); // move\n",
    "    Bad  b2 = std::move_if_noexcept(b1); // copy\n",
    "\n",
    "**Зачем?**\n",
    "\n",
    "Смысл в том, что копирующее создание обращаемо, т.е. если произошло исключение, то останется исходная валидная копия объекта - это и называется строгая гарантия безопасности исключений. Исключение при перемещении приведет к тому, что объект как минимум инвалидируется."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# <a id='toc3_'></a>[Гарантии безопасности исключений](#toc0_)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## <a id='toc3_1_'></a>[Гарантии безопасности исключений](#toc0_)\n",
    "\n",
    "**Гарантия отсутствия исключений**\n",
    "\n",
    "“Ни при каких обстоятельствах функция не будет генерировать исключения”.\n",
    "- главное условие - никакие исключения не покидают функцию\n",
    "- исключения если и происходят, то внутри функции они все и обрабатываются\n",
    "- именно такие функции обычно помечают noexcept\n",
    "\n",
    "**Базовая гарантия**\n",
    "\n",
    "“При возникновении любого исключения состояние программы останется согласованным”.\n",
    "- должно обеспечиваться для всех функций программы\n",
    "\n",
    "**Строгая гарантия** \n",
    "\n",
    "“Если при выполнении операции возникнет исключение, то программа останется том же в состоянии, которое было до начала выполнения операции”.\n",
    "- обеспечивается транзакционность, если началась некоторая операция и произошло исключение, то \"транзакция\" откатывается к предыдущему состоянию"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## <a id='toc3_2_'></a>[Строгая гарантия безопасности исключений](#toc0_)\n",
    "\n",
    "В каком случае мы не можем обеспечить строгую гарантию безопасности исключений?\n",
    "- При наличии взаимодействия со внешним окружением, т.е. необратимых действий (вроде отправки данных по сети и т.п.)\n",
    "\n",
    "Как обеспечить строгую гарантию безопасности исключений в остальных случаях?\n",
    "- Выполнять операцию над копией состояния программы.\n",
    "- Если операция прошла успешно, заменить состояние на копию.\n",
    "\n",
    "Когда можно обеспечить строгую гарантию эффективно?\n",
    "- По смыслу придется много копировать, соответственно, нужно минимизировать число операций копирования\n",
    "- Это вопрос архитектуры приложения.\n",
    "\n",
    "**Примеры**\n",
    "\n",
    "Когда **не получится обеспечить строгую гарантию безопасности исключений**\n",
    "\n",
    "- Передача данных по USB.\n",
    "- Передача файлов по Bluetooth\n",
    "- Копирование массива объектов типа std::string в std::ostream_iterator (может передавать данные куда угодно, на экран, в сеть и т.д.).\n",
    "\n",
    "Когда можно обеспечить:\n",
    "- Преобразование XML данных в оперативной памяти.\n",
    "- Копирование массива объектов типа std::string в std::list.\n",
    "- Сортировка массива объектов типа std::string (если мы изменили порядок элементов в массиве, как мы можем вернуть первоначальный порядок? сортировать не массив, а его копию)."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## <a id='toc3_3_'></a>[Как добиться строгой гарантии?](#toc0_)\n",
    "\n",
    "Пусть есть класс массива и метод изменения его размера `resize`\n",
    "\n",
    "    template<class T>\n",
    "    struct Array\n",
    "    {\n",
    "        void resize(size_t n)\n",
    "        {\n",
    "            T * ndata = new T[n];\n",
    "            for (size_t i = 0; i != n && i != size_; ++i) // до min(n,size_)\n",
    "                ndata[i] = data_[i];\n",
    "                \n",
    "            delete [] data_;\n",
    "            data_ = ndata;\n",
    "            size_ = n;\n",
    "        }\n",
    "\n",
    "        T * data_;\n",
    "        size_t size_;\n",
    "    };\n",
    "\n",
    "Проблемные места:\n",
    "1. `new` может бросить `bad_alloc`\n",
    "    - с т.з. безопасности исключений это не проблема, т.к. объект `Array` еще не менялся\n",
    "2. класс шаблонный и у типа `T` может быть конструктрор, который бросает исключения\n",
    "    - исключение может вылететь из любого из `n` конструкторов в `new`\n",
    "        - тоже не проблема, копилятор гаратирует, что при исключениях в конструкторах в `new` память будет освобождена, а данные `Array` опять же не менялись\n",
    "3. присваивание `ndata[i] = data_[i]`\n",
    "    - если будет исключение, то оно выйдет наружу, а указатель `T * ndata` останется не освобожденным (утечка памяти)\n",
    "\n",
    "Данный код не удовл. даже базовым гарантиям безопасности исключений, т.к. утечка памяти - это **несогласованное состояние программы**"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## <a id='toc3_4_'></a>[Как добиться строгой гарантии: вручную](#toc0_)\n",
    "\n",
    "Добавление трайкеч и обработка исключений\n",
    "\n",
    "    template<class T>\n",
    "    struct Array\n",
    "    {\n",
    "        void resize(size_t n) {\n",
    "            T * ndata = new T[n];\n",
    "            try {\n",
    "                for (size_t i = 0; i != n && i != size_; ++i)\n",
    "                    ndata[i] = data_[i];\n",
    "            } catch (...) {\n",
    "                delete [] ndata;\n",
    "                throw;\n",
    "            }\n",
    "            delete [] data_;\n",
    "            data_ = ndata;\n",
    "            size_ = n;\n",
    "        }\n",
    "\n",
    "        T * data_;\n",
    "        size_t size_;\n",
    "    };\n",
    "\n",
    "1. `new` обрабатывать не надо, более того, не надо вкладывать его в трайкеч, т.к. возможна ситуация, когда освобождение памяти (деструкторы) будет вызываться для несозданных элементов.\n",
    "2. присваивание, если вызовет исключение, то мы освободим выделенную память\n",
    "\n",
    "Утечки памяти нет, состояние массива не изменилось"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## <a id='toc3_5_'></a>[Как добиться строгой гарантии: RAII](#toc0_)\n",
    "\n",
    "Если у нас есть ресурс, который требует освобождения в случае исключений (например, память),то вместо отлавливания исключений вручную можно создать RAII-объект\n",
    "- RAII (Resource Acquisition Is Initialization) - идеома, когда получение некоторого ресурса неразрывно совмещается с инициализацией, а освобождение — с уничтожением объекта. Обычно реализуется передачей ресурса некоторому объекту на стеке, который получает ресурс в своем конструкторе и освобождает в деструкторе.\n",
    "\n",
    "Тут ресурс - это указатель, поэтому на помощь спешит умный указатель из STL. У него есть специализация для работы с массивами.\n",
    "\n",
    "\n",
    "    template<class T>\n",
    "    struct Array\n",
    "    {\n",
    "        void resize(size_t n) {\n",
    "            unique_ptr<T[]> ndata(new T[n]);\n",
    "            \n",
    "            for (size_t i = 0; i != n && i != size_; ++i)\n",
    "                ndata[i] = data_[i];\n",
    "\n",
    "            data_ = std::move(ndata);\n",
    "            size_ = n;\n",
    "        }\n",
    "\n",
    "        unique_ptr<T[]> data_;\n",
    "        size_t size_;\n",
    "    };\n",
    "\n",
    "Не только будет хранить в нем новый массив в `resize`, но и данные самого объекта. \n",
    "\n",
    "Если в присваивании возникнет исключение, то начнется сворачивание стека и деструктор локального `unique_ptr` освободит указатель. Исходное состояние объекта при этом не пострадает"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## <a id='toc3_6_'></a>[Как добиться строгой гарантии: swap](#toc0_)\n",
    "\n",
    "Для консервативных операций (где нет общения с \"внешним миром\") почти всегда доступен вариант с копированием данных программы и выполеннием операции над копией данных. Если возникнет исключение, то данные исх.объекта не пострадают.\n",
    "\n",
    "    template<class T>\n",
    "    struct Array\n",
    "    {\n",
    "        void resize(size_t n) {\n",
    "            Array t(n);\n",
    "            \n",
    "            for (size_t i = 0; i != n && i != size_; ++i)\n",
    "                t[i] = data_[i];    // какбэ для класса Array определен оператор [ ]\n",
    "            t.swap(*this);          // или swap(t) - без разницы\n",
    "        }\n",
    "\n",
    "        T * data_;\n",
    "        size_t size_;\n",
    "    };\n",
    "\n",
    "Создаем новый объект нужного размера, копируем в него объекты и есть все ОК, меняем местами с текущим объектом.\n",
    "\n",
    "Здесь используется тот факт, что операция `swap` обычно реализуется как `noexcept`"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "**Тест**\n",
    "\n",
    "Какие из следующих функций обеспечивают строгую гарантию безопасности исключений?\n",
    "\n",
    "    // НЕТ порядок не определен и если в new V исключение, то new T - утечка\n",
    "    std::pair<T*,V*> fun1() \n",
    "    {\n",
    "        return std::make_pair(new T, new V);\n",
    "    }\n",
    "\n",
    "    // НЕТ, порядок не определен и new T может упасть до того, как new V будет помещён в std::unique_ptr<T>()\n",
    "    std::pair<std::unique_ptr<T>,std::unique_ptr<V>> fun2() \n",
    "    {\n",
    "        return std::make_pair(\n",
    "                    std::unique_ptr<T>(new T),\n",
    "                    std::unique_ptr<V>(new V));\n",
    "    }\n",
    "\n",
    "    std::pair<std::unique_ptr<T>,std::unique_ptr<V>> fun3() \n",
    "    {\n",
    "        std::unique_ptr<T> pt(new T);\n",
    "        std::unique_ptr<V> pv(new V);\n",
    "        return std::make_pair(std::move(pt), std::move(pv));\n",
    "    }\n",
    "\n",
    "    void fun4(std::vector<std::string> & v)\n",
    "    {\n",
    "        std::reverse(v.begin(), v.end());\n",
    "    }\n",
    "    \n",
    "    // НЕТ, в fill идет присваивание, что потенциально может вызывать выделение памяти\n",
    "    void fun5(std::vector<std::string> & v, std::string const& s)\n",
    "    {\n",
    "        std::fill(v.begin(), v.end(), s);\n",
    "    }\n",
    "\n",
    "    void fun6(std::vector<std::string> & v, std::string const& s)\n",
    "    {\n",
    "        std::vector<std::string>(v.size(), s).swap(v);\n",
    "    }\n",
    "\n",
    "- смотрим возможную [реализацию](https://en.cppreference.com/)\n",
    "    - swap noexcept\n",
    "    - reverse использует iter_swap, который использует swap\n",
    "- где new в аргументах, порядок вычисления не определен, поэтому если второй кинет исключение, то первый не будет освобожден при сворачивании стека и останется аллоцированным (утечка)\n",
    "    - порядок вычисления НАСТОЛЬКО неопределен, что в `fun2` нет гарантий, что внутренние скобки предшествуют только внешним!!! Может так случиться, что сначала будет вызван один new, а потому другой new и только после этого создадутся unique_ptr, такой порядок допустим стандартом\n",
    "    - тут некая тонкость - на стек помещается вызов одного аргумента, если он отработал ОК, то он со стека снимается, а результат пишется в аргументы текущего фрейма. Поэтому при сворачивании стека к нему уже не будет доступа."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## <a id='toc3_7_'></a>[Проектирование с учётом исключений](#toc0_)\n",
    "\n",
    "Роль архитектуры.\n",
    "\n",
    "Рассмотрим традиционный интерфейс стека:\n",
    "    \n",
    "    template<class T>\n",
    "    struct Stack\n",
    "    {\n",
    "        void push(T const& t)\n",
    "        {\n",
    "            data_.push_back(t);\n",
    "        }\n",
    "\n",
    "        T pop()\n",
    "        {\n",
    "            T tmp = data_.back();\n",
    "            data_.pop_back();\n",
    "            return tmp;\n",
    "        }\n",
    "        \n",
    "        std::vector<T> data_;\n",
    "    };\n",
    "\n",
    "1. Метод `push` обесп.строг.гар.безоп.искл., т.к. `push_back` реализован как обеспечивающий строг.гар.безоп.искл. по стандарту(?) (хоть и не является `noexcept`).\n",
    "2. Метод `pop` возвращает элемент по значению, а значит копирует, что потенциально может вызвать исключение\n",
    "    - тогда элемент `tmp` будет утерян, соответственно обеспечивается только базовая гарантия безопасности исключений\n",
    "\n",
    "Итого:\n",
    "\n",
    "- Обеспечить строгую гарантию безопасности для метода pop, который возвращает выталкиваемый элемент, не получается из-за возможного исключения при копировании возвращаемого объекта.\n",
    "\n",
    "- Если у класса, объекты которого хранятся в стеке, есть небросающий перемещающий конструктор, то исходная реализация обеспечивает строгую гарантию безопасности исключений.\n",
    "\n",
    "```\n",
    "T a;\n",
    "a = b;      // оп.присваивания (перемещ. или нет не важно)\n",
    "T a1 = b;   // к.копирования (перемещ. или нет не важно)\n",
    "```\n",
    "\n",
    "- Проблема обеспечения строгой гарантии безопасности возвращающего метода pop актуальна для произвольных контейнеров."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## <a id='toc3_8_'></a>[Проектирование с учётом исключений (продолжение)](#toc0_)\n",
    "\n",
    "Будем возвращать по ссылке в аргументе.\n",
    "\n",
    "Рассмотрим традиционный интерфейс стека:\n",
    "\n",
    "    template<class T>\n",
    "    struct Stack\n",
    "    {\n",
    "        void push(T const& t)\n",
    "        {\n",
    "            data_.push_back(t);\n",
    "        }\n",
    "        \n",
    "        void pop(T & res)\n",
    "        {\n",
    "            res = data_.back();\n",
    "            data_.pop_back();\n",
    "        }\n",
    "        \n",
    "        std::vector<T> data_;\n",
    "    };\n",
    "\n",
    "Тогда `res` произойдет **присваивание** (копи или мув - не важно, главное - не установка указателя) и можно будет удалять элемент из стека.\n",
    "\n",
    "Минус - поменялась сигнатура на неудобную."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## <a id='toc3_9_'></a>[Использование unique_ptr](#toc0_)\n",
    "\n",
    "Будем возвращать элемент по указателю\n",
    "\n",
    "    template<class T>\n",
    "    struct Stack\n",
    "    {\n",
    "        void push(T const& t)\n",
    "        {\n",
    "            data_.push_back(t);\n",
    "        }\n",
    "\n",
    "        unique_ptr<T> pop()\n",
    "        {\n",
    "            % unique_ptr<T> tmp(new T(data_.back()));\n",
    "            data_.pop_back();\n",
    "            return std::move(tmp); // тут не надо мувить!!!!!\n",
    "        }\n",
    "        \n",
    "        std::vector<T> data_;\n",
    "    };\n",
    "\n",
    "Создается в куче объект - элемент вершины стека, и оборачивается в умный указатель.\n",
    "\n",
    "Вместо к.копирования для типа Т, кот. может бросить исключение, используется перемещ.конструктор умного указателя, который не бросает исключения.\n",
    "\n",
    "Минус - получили неестественную сигнатуру для данного метода с уникальным указателем.\n",
    "\n",
    "*) при возвращении локального объекта функции (каким и является `tmp`) по значению будет вызываться перемещающий конструктор. Плюс, без `std::move` компилятору позволяется сделать оптимизацию возвращаемого значения (RVO), и потенциально оно должно работать эффективнее\n",
    "\n",
    "неполный список случаев, когда будут вызываться перемещающие методы:\n",
    "\n",
    "- если передавать в них объект при помощи std::move();\n",
    "- если передавать в них временный объект;\n",
    "- если из функции по значению возвращается локальный объект функции."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "**Проблема архитектуры**\n",
    "\n",
    "Тут мы пытались в одном методе решить 2 задачи - вернуть вершину и удалить ее из стека, все получается коряво и неудобно, хоть и будет работать.\n",
    "\n",
    "В STL аналогичный стек сделали из двух методов `pop()` - удаляет, `top()` - возвращает вершину, и это правильно!"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## <a id='toc3_10_'></a>[Заключение](#toc0_)\n",
    "\n",
    "- Проектируйте архитектуру приложения с учётом исключений.\n",
    "- Функции, не бросающие исключения, нужно объявлять как noexcept.\n",
    "- Все использующие исключения функции должны обеспечивать как минимум базовую гарантию безопасности исключений.\n",
    "- Там, где это возможно, старайтесь обеспечить строгую гарантию безопасности исключений.\n",
    "- Используйте swap, умные указатели и другие RAII объекты для обеспечения строгой безопасности исключений."
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.10.8 ('py310')",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.10.8"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "53d00ba0b92f737b23b3e678e3a3ceb3fe4e948ad1ab95d9c6fdcbb4b4ec65f3"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
